# This database file represent any instance of database that can be connected and used in any plugin of Altair
# This config is environment agnostic, so it can be used in any environment based on it's environment variables.
# This is the sample of database config:
# <database_name>: string               - The database instance name
#   <example>
#   driver: string                            - Database driver used, required. Available: mysql
#   database: string                          - Database name, required.
#   username: string                          - Username of the databases,  required.
#   password: string                          - Database passwords, can be left empty.
#   host: string                              - Database host location, required.
#   port: string || integer                   - Database port, if left empty then will be use default value: 3306.
#   migration_source: string                  - Every database instance need a migration path.
#   connection_max_lifetime: string           - Set max connection lifetime duration.
#   max_iddle_connection: string | integer    - Set max iddle connection of the databases, if left empty then will be set unlimited.
#   max_open_connection: string | integer     - Set max open connection of the databases, if left empty then will be set unlimited.

main_database:
  driver: mysql
  database: {{ env "DATABASE_NAME" }}
  username: {{ env "DATABASE_USERNAME" }}
  password: {{ env "DATABASE_PASSWORD" }}
  host:     {{ env "DATABASE_HOST" }}
  port:     {{ env "DATABASE_PORT" }}
  migration_source: "file://migration"
  connection_max_lifetime: 120s
  max_iddle_connection: 100
  max_open_connection: 100
